---

- name: Launch backend instance 1
  docker_container:
    name: backend-1
    image: theov07/api_backend:latest
    ports:
      - "8081:8080"
    networks:
      - name: app-network

- name: Launch backend instance 2
  docker_container:
    name: backend-2
    image: theov07/api_backend:latest
    ports:
      - "8082:8080"
    networks:
      - name: app-network